# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\":\n\x07Request\x12\x16\n\x0e\x66irst_variable\x18\x01 \x01(\x05\x12\x17\n\x0fsecond_variable\x18\x02 \x01(\x05\"\x14\n\x05Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\x30\n\x0cSummaService\x12 \n\nSummaOfTwo\x12\x08.Request\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=17
  _globals['_REQUEST']._serialized_end=75
  _globals['_REPLY']._serialized_start=77
  _globals['_REPLY']._serialized_end=97
  _globals['_SUMMASERVICE']._serialized_start=99
  _globals['_SUMMASERVICE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
